# Generated by Django 5.2 on 2025-05-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_userprofile_managers_alter_userprofile_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Internship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(blank=True, default='')),
                ('company', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('url_link', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], default='freshman', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('draft', 'draft'), ('inprogress', 'in progress'), ('published', 'published')], default='draft', max_length=20, verbose_name='status'),
        ),
    ]
