# Generated by Django 5.2 on 2025-05-11 18:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_internship_alter_article_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='internship',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='internships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship',
            name='url_link',
            field=models.CharField(max_length=200),
        ),
    ]
