# Generated by Django 5.2 on 2025-05-12 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_internship_creator_alter_internship_url_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship',
            name='company',
            field=models.CharField(max_length=100, verbose_name='company'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='content',
            field=models.TextField(blank=True, default='', verbose_name='content'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='location',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='status',
            field=models.CharField(choices=[('freshman', 'Freshman'), ('sophomore', 'Sophomore'), ('junior', 'Junior'), ('senior', 'Senior')], default='freshman', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='title',
            field=models.CharField(max_length=100, verbose_name='title'),
        ),
        migrations.AlterField(
            model_name='internship',
            name='url_link',
            field=models.URLField(verbose_name='url_link'),
        ),
    ]
